<?php

namespace AppBundle\Repository;

/**
 * AwayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AwayRepository extends \Doctrine\ORM\EntityRepository
{
}
