<?php

namespace AppBundle\Repository;

/**
 * ShirtsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShirtsRepository extends \Doctrine\ORM\EntityRepository
{
}
