<?php

namespace AppBundle\Repository;

/**
 * ShortsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShortsRepository extends \Doctrine\ORM\EntityRepository
{
}
