<?php

namespace AppBundle\Repository;

/**
 * ThirdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThirdRepository extends \Doctrine\ORM\EntityRepository
{
}
